# Задание 1: Создание и манипуляции с тензорами.

## 1.0. Импорт библиотеки и создание девайса.

In [2]:
import torch

# Введём устройство, на котором будут работать тензоры.
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print(f"Тензоры на {device}.")

Тензоры на cuda:0.


## 1.1. Создание тензоров

In [56]:
tensor_rand = torch.rand(3, 4).to(device)
tensor_zeros = torch.zeros(2, 3, 4).to(device)
tensor_ones = torch.ones(5, 5).to(device)
tensor_arange = torch.arange(0, 16).reshape(4, 4).to(device)

print(f"- Тензор размером 3x4, заполненный случайными числами от 0 до 1:\n {tensor_rand}", end='\n\n')
print(f"- Тензор размером 2x3x4, заполненный нулями:\n {tensor_zeros}", end='\n\n')
print(f"- Тензор размером 5x5, заполненный единицами:\n {tensor_ones}", end='\n\n')
print(f"- Тензор размером 4x4 с числами от 0 до 15 (используйте reshape):\n {tensor_arange}")

- Тензор размером 3x4, заполненный случайными числами от 0 до 1:
 tensor([[0.2945, 0.6872, 0.6960, 0.8122],
        [0.9657, 0.4771, 0.0914, 0.0047],
        [0.5967, 0.7749, 0.9755, 0.4109]], device='cuda:0')

- Тензор размером 2x3x4, заполненный нулями:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], device='cuda:0')

- Тензор размером 5x5, заполненный единицами:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

- Тензор размером 4x4 с числами от 0 до 15 (используйте reshape):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], device='cuda:0')


## 1.2. Операции с тензорами

In [57]:
A = torch.arange(0, 12).reshape(3, 4).to(device)
B = torch.arange(0, 12).reshape(4, 3).to(device)

print(f"*Тензор А:\n {A}", end='\n\n')
print(f"*Тензор B:\n {B.T}", end='\n\n')

print(f"Транспонирование тензора:\n {A.T}", end='\n\n')
try:
    print(f"Матричное умножение:\n {A @ B}", end='\n\n')
except RuntimeError:
    print(f"Матричное умножение:\n {A.cpu() @ B.cpu()}", end='\n\n')
print(f"Поэлементное умножение A и транспонированного B:\n {A * B.T}", end='\n\n')
print(f"- Вычислите сумму всех элементов тензора A: {A.sum()}")

*Тензор А:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], device='cuda:0')

*Тензор B:
 tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]], device='cuda:0')

Транспонирование тензора:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]], device='cuda:0')

Матричное умножение:
 tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

Поэлементное умножение A и транспонированного B:
 tensor([[  0,   3,  12,  27],
        [  4,  20,  42,  70],
        [ 16,  45,  80, 121]], device='cuda:0')

- Вычислите сумму всех элементов тензора A: 66


## 1.3. Индексация и срезы

In [5]:
tensor = torch.arange(0, 125).reshape(5, 5, 5).to(device)
print(f"*Тензор:\n {tensor}", end='\n\n')

print(f"- Первая строка: {tensor[0, 0]}\n")
print(f"- Последний столбец:\n {tensor[:, :, 4]}\n")
print(f"- Подматрица размером 2x2 из центра тензора:\n {tensor[2, 1:3, 1:3]}\n")
print(f"- Все элементы с четными индексами:\n {tensor[:, :, ::2]}")

*Тензор:
 tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]], device='cuda:0')

- Первая строка: tensor([0, 1, 2, 3, 4], device='cuda:0')

- П

## 1.4. Работа с формами

In [59]:
tensor = torch.arange(0, 24).to(device)
tensor_2x12 = tensor.reshape(2, 12)
tensor_3x8 = tensor.reshape(3, 8)
tensor_4x6 = tensor.reshape(4, 6)
tensor_2x3x4 = tensor.reshape(2, 3, 4)
tensor_2x2x2x3 = tensor.reshape(2, 2, 2, 3)

print(f"- 2x12:\n {tensor_2x12}", end='\n\n')
print(f"- 3x8:\n {tensor_3x8}", end='\n\n')
print(f"- 4x6:\n {tensor_4x6}", end='\n\n')
print(f"- 2x3x4:\n {tensor_2x3x4}", end='\n\n')
print(f"- 2x2x2x3:\n {tensor_2x2x2x3}", end='\n\n')

- 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]], device='cuda:0')

- 3x8:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]], device='cuda:0')

- 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]], device='cuda:0')

- 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], device='cuda:0')

- 2x2x2x3:
 tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]], device='cuda:0')

